### ISSUE TITLE
Update quick MAPS selection sidebar to choose Diet or Biomarker data

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#300]
# Summary

Replace the "Population group" selection box with a toggle for the "Measure of MND"

<img width="295" alt="Screenshot 2021-02-25 at 10 33 14" src="https://user-images.githubusercontent.com/39411049/109329000-fef3b280-7851-11eb-84a0-41f396f97e5e.png">

Display the type of data in the summary card with the other search options:

![mnd](https://user-images.githubusercontent.com/72566636/109631538-f21adb80-7b3d-11eb-9d2d-083e627db50b.png)

# Details

The two toggle options must be able to be disabled via parameter from the API.  The `/micronutrient` endpoint will indicate whether the chosen MN supports Diet, Biomarker or both forms of data

# Acceptance Criteria

- [x] Population group selection removed from UI
- [x] Population group removed from router params
- [x] Toggle boxes to select either `Diet Data` or `Biomarker Data`
- [x] URL of selected page dependent on which measure is selected either `\diet` or `\biomarker` (See #298)

**Comment by jon571** [comment]
Adding @pautva for ref.

I'm not sure this diet/biomarker toggle really works in the sidebar.  It might look like it does on the quickmaps root location search page, but what happens when you're in the baseline page?  You can't change it then.  It will never show "biomarker" selected then.

I suggest we redesign this to have two buttons (links) at the bottom of the sidepanel, where the "View Results" button/link is currently (hidden when not on root location select page).  One that says something like "View Diet Data" and one "View Biomarker Data".  On the other pages that show the sidebar we can show the buttons but disable the one for the current data page.

**Comment by bgsandan** [comment]
Is the issue to do with the routing/page loadings?

If you select diet data and it takes you to `quick-maps/diet/baseline?country-id=MWI&...` can't selecting the toggle to biomarker then just take you to `/quick-maps/biomarker?country-id=MWI` and vice versa?

It may be I haven't understood the problem you're explaining, sorry!

**Comment by jon571** [comment]
Thing is that all the other controls affect what's on the current page.  What you're suggesting would do this on the location search page, but on the diet/biomarker pages the toggles all of a sudden turn into a set of links that navigate somewhere else.

This selection can also change the Data option(s) in the bottom select, although this is limited to a single item so it's not really an issue.

It also raises the question what happens if a user is on the baseline page and changes the vitamin that's selected to one that is only biomarker, not diet.  Does that then navigate to the biomarker page(s)?

I suppose if we're happy with this then that's fine.  It's just quite a bit different from what we had:
Selections changing the currently viewed content -> Selections replacing the current content with potentially completely different content.

**Comment by bgsandan** [comment]
Ok, I think i get your point. My only concern is that in terms of the logical user flow through the sidebar, the selection of diet or biomarker data comes before the data options select.  Whilst in quick MAPS the data options will only display one option, it will differ depending on whether the user selected diet/biomarker (as well as country/mn).  Later on, in other modules, there will be more than one option.

**Comment by bgsandan** [comment]
Re: your query of "what happens if a user is on the baseline page and changes the vitamin that's selected to one that is only biomarker, not diet. Does that then navigate to the biomarker page(s)?" - I guess there are two options - 1 switch to the page (possibly with the snack bar as discussed in the other issue) or 2: display a larger error message on the page about lack of appropriate data and pointing the user to switch data mode. No.1 probably the cleaner

**Comment by jon571** [comment]
As long as we've thought that through it's fine.  I'll get some updates merged in then try and resolve the navigation changes as well as query params and routeGuards for the new options etc.  Then we can see it all in action. :-)

**Comment by bgsandan** [comment]
Ok, thanks for raising it, it is good to talk through these things and their implications!  I reckon as you say, we'll go with it for now and see it all in action.  Hopefully won't need to unpick too much in the future, but hey that is the nature of agile development 😄

**Comment by pautva** [comment]
We probably don't want the information on the dashboard to change without the user knowing about it. But as long as they are informed about those changes and they are clearly visible, it should be ok.

When the measure of MND changes as a result of changing MN, snackbar could inform about that change. And the summary card should also show what data was loaded:

![change-measure](https://user-images.githubusercontent.com/72566636/110001717-92265f80-7d0c-11eb-9fe9-19a83ae036a1.png)

**Comment by jon571** [comment]
#368 should complete this issue.

**Comment by jon571** [comment]
We can add notifications in as suggested by Paulius after #338 has been merged.
