### ISSUE TITLE
Add example sample citation to the download tab of all cards

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#487]
Beneath the download options should be an example citation for using the data/outputs in a publication.

*   [x] Example citation text is defined (Action: @LouiseAnder ). This will likely be fixed across all cards but may contain dynamic content (e.g. current date)
*   [x] Citation text is displayed beneath the download file options
*   [x] Citation text can be copied to clipboard by clicking a "Copy" button
*   [x] Ability to download the reference as either plain text or bibtex (split button?)

**Comment by LouiseAnder** [comment]
Thanks @bgsandan I think the below is good where  _year_ and _dd mmm yyyy_ are replaced by 'live' content. Suggesting _dd mmm yyyy_, e.g. 01 Jun 2021, because this will be internationally understood (unlike 01/06/21 which can also be read as 6th Jan 2021).  No need for italics in actual citation. 

Suggested citation for this output: MAPS (_year_) The Micronutrient Action Policy Support (MAPS) Tool project. https://tool.micronutrient.support/ Accessed _dd mmm yyyy_.

**Comment by Sveouu** [comment]
completed 3 out of 4 pushed up on branch sr_487_download_text
@bgsandan, I am not familiar with bibtex, what would a caption in bibtex look like?
would it be similar to:

@MISC{MAPS (2021),
    author = {{The Micronutrient Action Policy Support (MAPS) Tool project}},
    title = {The Micronutrient Action Policy Support (MAPS) Tool project},
    year = {2021},
    note = {[Online; accessed June 01, 2021]},
    url = {https://tool.micronutrient.support/}
}
![image](https://user-images.githubusercontent.com/72437441/120345271-3b6ff800-c2f2-11eb-8651-eccd11ca3070.png)

**Comment by bgsandan** [comment]
Yep, I think something like that looks perfect!

**Comment by LouiseAnder** [comment]
Looks great, thank you! Will it also appear on the downloaded chart/map etc? I think we discussed that too @bgsandan but not sure how neatly it sits in practice?

**Comment by bgsandan** [comment]
The content to be displayed on the actual figure image itself is another issue (to be created but not forgotten!)

**Comment by Sveouu** [comment]
all above tasks completed & changes merged into develop
