### ISSUE TITLE
Household dietary supply card updates

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#488]
![](https://user-images.githubusercontent.com/39411049/120289701-786bc880-c2b9-11eb-8561-c972c6479a37.png)

*   [x] Add y-axis label "Count"
*   [x] Remove 'Frequency' legend
*    [x]  Add x-axis label "\<micronutrient.name> in \<micronutrient.unit>/capita/day".  Data from the "/micronutrient" endpoint called in the sidebar.  E.g. "zinc in mcg/capita/day"
*   [x] Threshold line should be vertical not horizontal i.e. from around ~580 (in above example) on the x-axis rather than y-axis

**Comment by Sveouu** [comment]
completed 3 out of 4, unsure how to add a vertical line annotation to the histogram.

pushed changes up on branch sr_488_household_card_updates

**Comment by bgsandan** [comment]
The histogram on the biomarker pages has a vertical line.  That may be a good place to have a peek to see what can be borrowed:

![](https://user-images.githubusercontent.com/39411049/120444197-4f157000-c37f-11eb-8d02-54b29a47924f.png)

**Comment by Sveouu** [comment]
On the biomarker info histogram the vertical line for the abnormal threshold only appears because its threshold value coincides with one of the bin values (abnThreshold =150), where it does not coincide ( i.e defThreshold = 70) the line does not appear.

I could not find a workaround as the x axis represents bins rather than a continues numerical axis where the thresholds could be placed.

**Comment by Sveouu** [comment]
@bgsandan @Fuhji Going to leave this issue open, have not addressed the last point as I have not figured out how to add the vertical annotation to the histogram.

**Comment by Sveouu** [comment]
closing issue vertical line has been added , but reopening #622 as the threshold appearance has not been solved
